- name: Loading the Variable  while executing the play book
  hosts: local
  connection: local
  vars_prompt:
  - name: Username 
    prompt: Enter your user name
    private: false

  - name: Password 
    prompt: Enter your Password
    private: true
  tasks:
  - name: Take user name and password while executing the play book
    ansible.builtin.debug:
      msg: Your user name {{Username}}, and {{Password}}