 - name: Learning loops in Ansible
   hosts: local
   connection: local
   tasks:
   - name: Print facts
     ansible.builtin.debug:
       msg: "Hello {{item}}"
     loop:
     - Linux
     - Shell
     - Ansible