- name: Manipulating data with Filters
  hosts: local
  connection: local
  become: yes

  vars:
    Topics: "Linux,Shell,Ansible"   # STRING
    StudentMap:                    # MAP
      Name: Kranthi
      Course: "DevOps"
      Duration: "4 months"

  tasks:

    - name: Learning default filter with piping
      ansible.builtin.debug:
        msg: "This information is related to {{ kranthi | default('education') }}"

    - name: String to List
      ansible.builtin.debug:
        msg: "{{ Topics | split(',') }}"

    - name: Map to List
      ansible.builtin.debug:
        msg: "{{ StudentMap | dict2items }}"
