- name: Manipulating data with the Filters
  hosts: local
  connection: local
  become: Yes
  vars: 
    Topics: Linux, Shell, Ansible # String
    StudentMap: # Map
      Name: Kranthi
      Course: "Devops
      Duration: 4 months

  tasks:
  - name: This task is used for learing default with piping # directly use the variables without declaring
    ansible.builtin.debug:
      msg: "This information related to, {{ KRANTHI | default('education') }}"

  - name: String to List
    ansible.builtin.debug:
      msg: "{{ Topics |  split(',') }}"

  - name: Map to List
    ansible.builtin.debug:
      msg: "{{ StudentMap | dict2items }}"
   




    
